api_platform:
    title: FUNDED
    version: 1.0.0
    formats:
        jsonld: ['application/ld+json']
    # Good defaults for REST APIs
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
    resource_class_directories:
        - '%kernel.project_dir%/src/Entity'
        - '%kernel.project_dir%/src/Enum'
